### PR TITLE
Test with mambabuild

### PR DESCRIPTION
**Pull request by mariusvniekerk**
…0, and conda-forge-pinning 2021.10.13.20.28.53

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@mariusvniekerk, what's the purpose of this PR?
Please be careful that this feedstock is really expensive in terms of CPU hours.

**Comment by beckermr** [comment]
This package builds when mamba is not used, so something is happening there.

**Comment by wolfv** [comment]
I am happy to look into this more tomorrow (quite later over here in Europe). Still unsure what's going on -- maybe there is some pre-processing that's missed in the mambabuild -- or maybe what Isuru just pushed will fix it, let's see! :)

**Comment by beckermr** [comment]
Sorry @wolfv! Not trying to push you at all. Just writing down my thinking for why this is odd. Get some sleep and thank you for all of the hard work!

**Comment by wolfv** [comment]
There is also the defaults channel that's removed though

**Comment by mariusvniekerk** [comment]
Nicely found @isuruf

**Pull request closed without merging**
