### PR TITLE
Patch GNU openmp to be fork safe

### PR DESCRIPTION
**Pull request by davidbrochart**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by davidbrochart** [comment]
@beckermr I inserted a syntax error in the patch file. I can see the patch is applied but obviously too late because it doesn't fail. Where should it be applied?

**Comment by isuruf** [comment]
Patches should go in crosstool-ng. https://github.com/conda-forge/crosstool-ng-feedstock uses https://github.com/ContinuumIO/crosstool-ng and a patch for gcc 7.3.0 should go in https://github.com/ContinuumIO/crosstool-ng/tree/master/packages/gcc/7.3.0

**Comment by beckermr** [comment]
Got it @isuruf. I am still strongly not in favor of merging this into the main conda-forge compilers unless we use the version that is finally accepted upstream.

**Comment by davidbrochart** [comment]
@beckermr I know but the original author of the patch doesn't have time to spend on it any more, and he's much more qualified than me to try and push it upstream.

**Comment by beckermr** [comment]
Then I think we have to wait. OpenMP is a core standard used by tons of projects. We simply cannot potentially ship a buggy OpenMP implementation.

**Comment by davidbrochart** [comment]
Sure, putting that on hold then.

**Pull request closed without merging**
