### PR TITLE
Update gcc minor versions

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by beckermr** [comment]
This effort is noble. Should we just push gcc 9 out the door instead?

**Comment by isuruf** [comment]
That's a bigger task that I don't want to take on right now.

**Comment by scopatz** [comment]
LGTM - but CI is failing

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Pull request merged**
