### PR TITLE
Fix libgcc.so symlink in sysroot

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
is this still necessary? all red.

**Comment by isuruf** [comment]
Yes, need to fix this for clang.

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

(local rerender seemed to hang; no progress after ~20+ min)

**Comment by h-vetinari** [comment]
Rerender is broken, removed.

**Comment by hmaarrfk** [comment]
I remember that rerendering this takes about 40 mins ;)

tmux + go do something else!

**Comment by beckermr** [comment]
I did see a bug in smithy where you have to rerender twice and it alternates between a good one and a bad if I remember correctly. I never tracked it down. That might have been for this feedstock. I am not sure.

**Comment by h-vetinari** [comment]
@isuruf, I may have fixed this now. 🙃

**Comment by isuruf** [comment]
Thanks

**Comment by h-vetinari** [comment]
So the cross-compiled s390x targets are failing with
```
libtool: install: warning: relinking `libasan.la'
libtool: install: ...
libtool: relink: ...
collect2: fatal error: ld terminated with signal 9 [Killed]
```
but the native s390x compilers passed, so this should sort itself out upon restart I guess...

IMO we should merge and see (not least given the lack of usage of s390x compilers) - WDYT?

**Comment by isuruf** [comment]
Come on. What's the hurry? You are not even a maintainer of this repository.

**Comment by isuruf** [comment]
I'm removing this commit and resending the PR.

**Pull request merged**
