### PR TITLE
ENH add extra sysroot deps to mark builds

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR adds a few extra sysroot deps to mark the builds for the C/C++/FORTRAN compilers as belonging to the new sysroots. This enables us to use a repodata patch for the vendored sysroot versions of these compilers (https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/66).

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
ok @isuruf @conda-forge/core this is the last PR we need to enable cos7!

**Comment by isuruf** [comment]
Shouldn't the activation packages also need a conflict with `sysroot_*`? Otherwise the old activation packages will be used with this new package.

**Comment by beckermr** [comment]
> Shouldn't the activation packages also need a conflict with sysroot_*? Otherwise the old activation packages will be used with this new package.

Why do the activation packages care about the sysroot stuff?

**Comment by beckermr** [comment]
@#!$@#!$@#!

How did I not know about this?!

UGH. Will make a PR and send repodata patches today. :/

**Comment by beckermr** [comment]
OK. I have the PR for the depo data patches here: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/68

We'll have to merge this PR after the repo data patches.

Then we can merge a PR (to be made) to rebuild the activation scripts.

**Comment by beckermr** [comment]
Ok @isuruf, I think this one is ready to merge!

**Comment by jaimergp** [comment]
I think this PR is breaking `gfortran` tests for CMake 3.17. See [logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=188896&view=logs&j=e9afaa34-1a0f-534e-78fc-fae528ccd915&t=48395e60-bc5f-5e45-7455-d404f0c95f3a&l=729) for https://github.com/conda-forge/ambertools-feedstock/pull/41.

**Comment by beckermr** [comment]
fixed in https://github.com/conda-forge/ctng-compilers-feedstock/pull/33

**Pull request merged**
